/* REGION TRYOUT SCHEDULE */
const API_TRYOUT_SCHEDULE_LIST = '/tryout-schedule'
const API_TRYOUT_SCHEDULE_CREATE = '/tryout-schedule'
const API_TRYOUT_SCHEDULE_EDIT = '/tryout-schedule'
const API_TRYOUT_SCHEDULE_GET_DETAIL = '/tryout-schedule'
const API_TRYOUT_SCHEDULE_DELETE = '/tryout-schedule'

/* REGION TRYOUT SCHEDULE DETAIL */
const API_TRYOUT_SCHEDULE_DETAIL_LIST = '/tryout-schedule-detail'

/* REGION TRYOUT PACKET */
const API_TRYOUT_PACKET = '/tryout-packet'
const API_TRYOUT_PACKET_DETAIL = '/tryout-packet'
const API_TRYOUT_PACKET_STORE = '/tryout-packet'
const API_TRYOUT_PACKET_DELETE = '/tryout-packet'
const API_TRYOUT_PACKET_EDIT = '/tryout-packet'

/* REGION TRYOUT PACKET TYPE */
const API_TRYOUT_PACKET_TYPE = '/tryout-packet-type'
const API_TRYOUT_PACKET_TYPE_DETAIL = '/tryout-packet-type'
const API_TRYOUT_PACKET_TYPE_STORE = '/tryout-packet-type'
const API_TRYOUT_PACKET_TYPE_DELETE = '/tryout-packet-type'
const API_TRYOUT_PACKET_TYPE_EDIT = '/tryout-packet-type'

export {
        API_TRYOUT_SCHEDULE_LIST, 
        API_TRYOUT_SCHEDULE_CREATE,
        API_TRYOUT_SCHEDULE_DETAIL_LIST,
        API_TRYOUT_SCHEDULE_GET_DETAIL,
        API_TRYOUT_SCHEDULE_EDIT,
        API_TRYOUT_SCHEDULE_DELETE,
        API_TRYOUT_PACKET,
        API_TRYOUT_PACKET_DETAIL,
        API_TRYOUT_PACKET_STORE,
        API_TRYOUT_PACKET_DELETE,
        API_TRYOUT_PACKET_EDIT,
        API_TRYOUT_PACKET_TYPE,
        API_TRYOUT_PACKET_TYPE_DETAIL,
        API_TRYOUT_PACKET_TYPE_STORE,
        API_TRYOUT_PACKET_TYPE_DELETE,
        API_TRYOUT_PACKET_TYPE_EDIT
       }