/* QUESTION PACKET TYPE */

const API_QUESTION_TYPE_PACKET = '/question-packet-type'
const API_QUESTION_TYPE_PACKET_CREATE = '/question-packet-type'
const API_QUESTION_TYPE_PACKET_DETAIL = '/question-packet-type'
const API_QUESTION_TYPE_PACKET_EDIT = '/question-packet-type'
const API_QUESTION_TYPE_PACKET_DELETE = '/question-packet-type'

/* QUESTION PACKET */
const API_QUESTION_PACKET = '/question-packet'
const API_QUESTION_PACKET_CREATE = '/question-packet'
const API_QUESTION_PACKET_DETAIL = '/question-packet'
const API_QUESTION_PACKET_EDIT = '/question-packet'
const API_QUESTION_PACKET_DELETE = '/question-packet'

/* QUESTION */
const API_QUESTION = '/question'
const API_QUESTION_CREATE = '/question'
const API_QUESTION_DETAIL = '/question'
const API_QUESTION_EDIT = '/question'
const API_QUESTION_DELETE = '/question'

export {
    API_QUESTION_TYPE_PACKET,
    API_QUESTION_TYPE_PACKET_CREATE,
    API_QUESTION_TYPE_PACKET_DELETE,
    API_QUESTION_TYPE_PACKET_DETAIL,
    API_QUESTION_TYPE_PACKET_EDIT,
    API_QUESTION_PACKET,
    API_QUESTION_PACKET_CREATE,
    API_QUESTION_PACKET_DELETE,
    API_QUESTION_PACKET_DETAIL,
    API_QUESTION_PACKET_EDIT,
    API_QUESTION,
    API_QUESTION_CREATE,
    API_QUESTION_DELETE,
    API_QUESTION_DETAIL,
    API_QUESTION_EDIT,
}